import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'

const plusJakarta = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Home',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="fr" className="">
            <body
                className={`${plusJakarta.className} flex flex-col items-center bg-slate-100 p-5 dark:bg-slate-900`}
            >
                {children}
            </body>
        </html>
    )
}
